---
- hosts: all
  vars_files:
    - ../variables.yml

  tasks:
  - name: Install node on server
    become: true
    apt:
        name: nodejs
        update_cache: yes

  - name: Install npm on server
    become: true
    apt:
        name: npm
        state: present

  - name: Symlink nodejs and node
    become: true
    file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

  - name: Installing Python pip
    become: true
    apt:
        pkg: python-pip
        state: latest

  - name: Installing Python 3 pip
    become: true
    apt:
        pkg: python3-pip
        state: latest

  - name: Install nginx
    become: true
    apt:
        pkg: nginx
        state: latest
        update_cache: yes

  - name: Add mongo ppa key
    apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        state: present 
    become: true
    
  - name: Add mongo sources list
    apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/{{mongodb_version}} multiverse"
    become: true

  - name: Installing MongoDB
    become: true
    apt: 
        name: mongodb-org
        state: present
        update-cache: yes
        
    # notify:
    #     - start mongodb

  - name: Install the pymongo package
    become: true
    pip: 
        name: pymongo 
        state: latest
        use_mirrors: no

  - name: Start Mongo daemon
    become: true
    service:
        name: mongod
        state: started

  - name: Creating MongoDb user
    become: true
    mongodb_user:
        database: "admin"
        name: "admin"
        password: "root"
        roles: readWrite,dbAdmin
        state: present

  # - name: Checking for already cloned checkbox repository
  #   stat:
  #       path: "{{checkbox_folder}}"
  #   register: checkbox_repo

  - name: Cloning checkbox repository
    become: true
    git:
        repo: "https://github.com/reCursedd/checkbox.io.git"
        dest: "{{checkbox_folder}}"
        update: no
        force: yes
    #when: checkbox_repo.stat.isdir is not defined

  - name: Run npm install to install dependencies 
    become: true
    command: npm install
    args:
      chdir: "/home/vagrant/checkbox/server-side/site"

  - name: Replace package.json 
    become: true
    copy:
      src: "/ansible-server/templates/package.json"
      dest: "{{checkbox_folder}}/server-side/site"
      force: yes  

  - name: update location of public_html into default
    become: true
    replace:
        dest: "{{checkbox_folder}}/local-conf/default"
        regexp: "/Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html"
        replace: "{{checkbox_folder}}/public_html"

  - name: Copy default file to nginx folder
    become: true
    copy: 
        src: "{{checkbox_folder}}/local-conf/default"
        dest: "/etc/nginx/sites-available/default"
        remote_src: true
        mode: 0644

  - name: Copy nginx.conf file to diferent location
    become: true
    copy: 
        src: "{{checkbox_folder}}/local-conf/nginx.conf" 
        dest: "/etc/nginx/nginx.conf"
        remote_src: true
        mode: 0644

  - name: Install forever (to run Node.js app)
    become: true
    npm: 
        name: forever 
        global: yes 
        state: present

  - name: "Check list of Node.js apps running."
    command: forever list
    register: forever_list
    changed_when: false
        
  - name: Start application
    command: forever start {{checkbox_folder}}/server-side/site/server.js
    when: "forever_list.stdout.find('/home/vagrant/checkbox/server-side/site/server.js') == -1"

  - name: Restart nginx
    become: true
    service: 
        name: nginx 
        state: restarted 
        enabled: yes